### ISSUE TITLE
電書協CSSへの変更依頼

### ISSUE THREAD

**Issue by ghost** [kyukyunyorituryo/AozoraEpub3#1]
AozoraEpub3で使用されているCSSを電書協CSSへの変更をお願いします。
導入するメリットとしては使用する端末毎にCSSを変える必要がなく、非常に汎用性が高いEPUBの作成が可能になるためです。
各出版社のCSSを比較すると基本部分は電書協CSSを使い、それだけでは表現しきれない部分を補うため独自のCSSを作成しているようです。

ただ、端末によっては動作が遅くなるという報告があるようなので、電書協CSSをそのまま使うのではなく、少し軽量化したほうがいいかもしれません。
軽量化する際はCSSから、フォントサイズ指定等のタグを一つに絞ったり、使用頻度の低いタグを抜粋するといった形で進め、フルバージョンが必要な際は元のCSSを上書きすれば使用が可能になるようにしたいと思います。軽量化に関してはこちらで検討いたします。

何卒よろしくお願いいたします。

**Comment by kyukyunyorituryo** [comment]
電書協のEPUBに含まれているCSSは6つあって、fixed-layout-jp.cssは固定レイアウトと表紙にすでに追加しています。
book-style.cssでは、style-reset.css、style-standard.css、style-advance.cssをimportしているようです。
book-style.css、style-reset.css、style-standard.css、style-advance.cssをそのままか少し編集する形にするということでしょうか。AozoraEpubでは改行天付きなど電書協のスタイルシートだけでは足りない部分があるのでそのあたりどうするか。

**Comment by kyukyunyorituryo** [comment]
あれ、アカウント削除されましたか。
電書協のEPUBのCSSに寄せていきたいとは思っているけど、どういう形の完成形が良いかを考えて置き換えないと複雑になりそうです。

**Comment by kyukyunyorituryo** [comment]
まだ、見ているかどうか走らないけれど、電書協準拠とは言わないけど、電書協のCSSは使うようにかえた。

book-style.cssはAozoraEpub3であった元々の注記でしか表現できなかった部分を読み込んでいる。今後このスタイルシート内容や読み込むファイル名は変わる可能性がある。
font.css内の記述をbook-style.cssに移す可能性がある。
単ページ画像のimage.cssは今後、fixed-layout-jp.cssを使ってSVGラッピング化するかもしれない。今はまだ、電書協のスタイルシートの記述ではない。表紙画像はfixed-layout-jp.cssを使ってSVGラッピング化している。表紙画像のサイズのリサイズ機能を削除するかもしれない。
左右中央（扉）は電書協で記述がなかったので、AozoraEpub3のママ書いている。AozoraEpub3ではキンドルだけ別の書き方になっている。

実際どこまでバグが有るかは検証してみないとなんとも言えない。

https://github.com/kyukyunyorituryo/AozoraEpub3/releases/tag/1.1.1b1Q

**Comment by kyukyunyorituryo** [comment]
最新バージョンでは、ほとんど電書協CSSを使うようになったのでクローズします。
