### ISSUE TITLE
バージョン 1.1.1b21Q の問題

### ISSUE THREAD

**Issue by happynow** [kyukyunyorituryo/AozoraEpub3#14]
最新版 1.1.1b21Q を試したところ、以下の問題が見つかりました。
細かい問題なので纏めさせて頂きました。

### 1. 操作画面のラベルの文字切れ
操作画面の詳細設定タブにある「行頭字下げ」のラベルが文字切れして「行頭字…」と表示されています。
「非日本語環境での日本語フォントの使用」の対応の影響かもしれません。

### 2. 小説家になろうサイトから100話しか取得できない
次のふたつのファイルで

web/ncode.syosetu.com/extract.txt
web/novel18.syosetu.com/extract.txt

下記のように NEXTPAGE がコメントアウトされていたことが原因だと思います。

```
#NEXTPAGE	.novelview_pager-next
```
### 3. CSSセレクタの誤記
偶然、見つけました。下記のとおり、CSSセレクタで `.vtrl` が重複しています。

https://github.com/kyukyunyorituryo/AozoraEpub3/blob/91b9d758a0487b2eceae972cdf89ce1b94ffe2dd/template/item/style/aozora.css#L266-L267

**Comment by kyukyunyorituryo** [comment]
１と３は対応しました。
https://github.com/kyukyunyorituryo/AozoraEpub3/commit/2d5061572e0658779e5a0c9e02d1d30ca561caf4
https://github.com/kyukyunyorituryo/AozoraEpub3/commit/fb30fef868dffc8cfc8030076cc07bf230e8f48d
２は小規模テストのために初期設定では有効化していないとリリースノートに書いてあります。

**Comment by happynow** [comment]
2については失礼しました。確認が足らなかったです。
修正版ダウンロードし確認しました。問題ありませんでした。

あと伝え忘れたので追記させて頂きます。
些細なことですが
「電書協 EPUB 3 制作ガイド ver.1.1.3[^1]」の76ページには、版元のCSSについては

> (style-***.css) …… 版元別スタイルセット（各社、必要なら用意。表示は自己責任）

と書かれているので aozora.css の名前は style-aozora.css とすることも考えられます。
（ text.cssや font.css は style-aozora.css にインポートしても良いかも）
このあたりは特に拘りはありませんか。
動作に影響するわけではないので、このままでも何も問題ありません。

[^1]: http://ebpaj.jp/counsel/guide からダウンロードした  「電書協 EPUB 3 制作ガイド ver.1.1.3 2015年1月1日版」.zip の 20150101-ebpaj-guide-v113.pdf

**Comment by happynow** [comment]
>（ text.cssや font.css は style-aozora.css にインポートしても良いかも）

と書いたのは、ファイルを統合するというわけではなく
`aozora.css` あるいは `style-aozora.css` のなかで `@import` する、という意味です。
```css
/* aozora.css のなかでインポート */
@charset "utf-8";
@import "font.css";
@import "text.css";
@namespace "http://www.w3.org/1999/xhtml";
```

ちなみに、もしこれを行うなら `@import` 文は `@namespace` より先に書いて下さい。

MDNには、`@import` ルールは他のアットルールより先に書く（`@charset` and `@layer`を除く）ように注意があります。
> @&#x200b;import rule must be defined at the top of the stylesheet, before any other at-rule (except @&#x200b;charset and @&#x200b;layer) and style declarations, or it will be ignored.
>
> MDN web docs [References > CSS > @import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)
> 日本語ページには誤訳があったため、原文を引用


提案しておいて何ですが、この辺り拘りありません。特に対応しなくてもよいと思います。

**Comment by happynow** [comment]
別件で知りたいことが、ご返信に書いてありました。ありがとうございます。

**Comment by happynow** [comment]
度々すいません。「電書協 EPUB 3 制作ガイド ver.1.1.3」の10ページに

> @import ルールの採用
> @import で読み込まれたファイル内で、さらに @import を用いることは推奨しない。

と書いてありました（なぜ？）
いずれにしても駄目でした。すいません。

**Comment by happynow** [comment]
v1.1.1b22Qで直っていることを確認しました。
対応ありがとうございました。
