### ISSUE TITLE
カクヨムの一部作品につき著者名が出版社名になってしまう

### ISSUE THREAD

**Issue by happynow** [kyukyunyorituryo/AozoraEpub3#15]
カクヨムのサイトにおいて、著者表記が「著者名／出版社名」となっている作品[^1]をダウンロード変換すると、著者名が出版社名だけになってしまいます。
Version: 1.1.1b21Q

[^1]: https://kakuyomu.jp/official のページを開くといくつか見つかります。

**Comment by kyukyunyorituryo** [comment]
修正しました
https://github.com/kyukyunyorituryo/AozoraEpub3/commit/433bc1b9c5f53000995807ee2f615d40bf111faa

**Comment by happynow** [comment]
修正版を実行したところ「／著者名 出版社名」となってしまいました。
ソース確認させて頂きましたが、緑のラインのように直せば良さそうです。

`WebAozoraConverter.java`
```diff
367  String altauthor="";
368  if(episode.getJSONObject("Work:" + cd).optString("alternateAuthorName",null)!=null) {
-369      altauthor=altauthor + "／"+ episode.getJSONObject("Work:" + cd).getString("alternateAuthorName");
+369     altauthor = episode.getJSONObject("Work:" + cd).getString("alternateAuthorName") + "／";
370  }
```

**Comment by kyukyunyorituryo** [comment]
修正しました
https://github.com/kyukyunyorituryo/AozoraEpub3/commit/595b2b67f4e845d82e2ffd80e93a051acd557541

**Comment by happynow** [comment]
修正確認しました。対応ありがとうございました。
