### ISSUE TITLE
epubをsend_to_kindleした後にiPadのkindleアプリで表示すると意図通りに表示されない

### ISSUE THREAD

**Issue by y-bonfire** [kyukyunyorituryo/AozoraEpub3#26]
epubをsend_to_kindleした後にiPadのkindleアプリで表示すると意図通りに表示されないようです
- 縦書きなのが横書きになる
- ルビが表示されない

## 調べる過程でわかったこと１　calibreで再生成すると表示された
- PC版(Windows)のKindle、Kindle Previewer 3だと問題なかった

以下のような手順でepubをcalibreで再生成してからsend_to_kindleすると意図通りの表示になりました
- 一度epubにした後にcalibreでepubを読み込む
- その後にazw3で出力後にcalibreを終了
- azw3でcalibreで読み込んだ後にepubで出力
- そのepubをsend_to_kindle

## 調べる過程でわかったこと2 epubの中身の比較

- calibreで再生成したepubとAozoraEpub3で生成したepubを7zipで展開して比較しました
 - 仮説1  拡張子xhtmlを解釈できない？
   - AozoraEpub3で生成されたものは拡張子がxhtml、calibreのほうはhtmlだった
   - 下のURLでスタイルシートに触れられてますが、スタイルシートを読めてない気がします
- 仮説2 1と似ているけど、タグの構造に問題ある？
  - calibreが作るhtmlファイルとAozoraEpub3のhtmlファイルは構造が結構違うと感じた
    - calibreはdivタグやクラス指定でやっている
  - ブラウザやKindlePreviewerで表示できるので、アプリ側の問題といえる気がしました

```
calibreで再生成したepubの中のhtml
<p class="pcalibre1 pcalibre6 pcalibre"><ruby class="pcalibre1 pcalibre">寒蝉敗柳<rt class="pcalibre1 pcalibre">かんせんはいりゅう</rt></ruby>に鳴き大火西に向かいて流るる秋のはじめになりければ心細くも<ruby class="pcalibre1 pcalibre">三蔵<rt class="pcalibre1 pcalibre">さんぞう</rt></ruby>は二人の弟子にいざなわれ<ruby class="pcalibre1 pcalibre">嶮難<rt class="pcalibre1 pcalibre">けんなん</rt></ruby>を<ruby class="pcalibre1 pcalibre">凌<rt class="pcalibre1 pcalibre">しの</rt></ruby>ぎ道を急ぎたもうに、たちまち前面に一条の大河あり。大波<ruby class="pcalibre1 pcalibre">湧返<rt class="pcalibre1 pcalibre">わきかえ</rt></ruby>りて河の広さそのいくばくという限りを知らず。岸に上りて望み見るときかたわらに一つの石碑あり。上に<ruby class="pcalibre1 pcalibre">流沙河<rt class="pcalibre1 pcalibre">りゅうさが</rt></ruby>の三字を<ruby class="pcalibre1 pcalibre">篆字<rt class="pcalibre1 pcalibre">てんじ</rt></ruby>にて彫付け、表に四行の小<ruby class="pcalibre1 pcalibre">楷字<rt class="pcalibre1 pcalibre">かいじ</rt></ruby>あり。</p>

AozoraEpub3のepubの中のhtml
<div class="mt3"><p><ruby>寒蝉敗柳<rt>かんせんはいりゅう</rt></ruby>に鳴き大火西に向かいて流るる秋のはじめになりければ心細くも<ruby>三蔵<rt>さんぞう</rt></ruby>は二人の弟子にいざなわれ<ruby>嶮難<rt>けんなん</rt></ruby>を<ruby>凌<rt>しの</rt></ruby>ぎ道を急ぎたもうに、たちまち前面に一条の大河あり。大波<ruby>湧返<rt>わきかえ</rt></ruby>りて河の広さそのいくばくという限りを知らず。岸に上りて望み見るときかたわらに一つの石碑あり。上に<ruby>流沙河<rt>りゅうさが</rt></ruby>の三字を<ruby>篆字<rt>てんじ</rt></ruby>にて彫付け、表に四行の小<ruby>楷字<rt>かいじ</rt></ruby>あり。</p>
```

## 調べたURL
- iOSのKindleでepubを縦書き・ルビ表示する
https://note.com/atsu1166/n/nae986ab404e7#f47da447-7bae-467b-ac2f-f6cb75e37c73
参考になった。calibreを使うと良さそうだということがわかった

- macOS版、iOS版、iPadOS版のKindleで縦書き・ルビが表示されない問題
https://qiita.com/ynomura/questions/a8d38d24beffe60b81bc
ここで貼られている画像と同じ状況です

ここまで原因を調べてissueを作りながらまとめました
KindlePreviewerで表示されているものとアプリで表示が異なるということは、AmazonがiOSに出しているKindleアプリ側が対応すべき問題のようにも感じました

## Amazon側の対応

モバイルアプリの窓口はここらしい
https://jp.amazonforum.com/s/topic/0TO4P000000tAOwWAM/kindle%E7%84%A1%E6%96%99%E3%82%A2%E3%83%97%E3%83%AA-%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E7%89%88

同様の問い合わせが見つかるが、解決がされていない
例えば問題のepubを送って向こう側で調べてくれる、と一番スムーズだが、それは難しそう

- Send to Kindleで送ったEPUBのCSSが反映されない
https://jp.amazonforum.com/s/question/0D56Q0000BRrbW2SQJ/send-to-kindle%E3%81%A7%E9%80%81%E3%81%A3%E3%81%9Fepub%E3%81%AEcss%E3%81%8C%E5%8F%8D%E6%98%A0%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84

- aozoraepub3 アプリで作成したepubファイルで縦書き表示できない。
https://jp.amazonforum.com/s/question/0D56Q0000CYtkX4SQJ/aozoraepub3-%E3%82%A2%E3%83%97%E3%83%AA%E3%81%A7%E4%BD%9C%E6%88%90%E3%81%97%E3%81%9Fepub%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A7%E7%B8%A6%E6%9B%B8%E3%81%8D%E8%A1%A8%E7%A4%BA%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84

**Comment by y-bonfire** [comment]
2024/8/2 10:30 にAmazonのサポートにチャットで状況を伝えました
このissueが一番まとめられているのでURLも連絡済です
その際に問題が再現するかの確認も行いました
念の為スクリーンショットも貼っておきます

PCでは縦書き、iPadでは横書き(CSSが読めてない)になっている

iPad(アプリversion 7.15.1)
![911B6826-D335-46AB-ABB7-51DA1F28ACB0](https://github.com/user-attachments/assets/416b3f3c-88f8-4c6d-b70f-ca298d86f965)

PC版
![スクリーンショット 2024-08-02 104208](https://github.com/user-attachments/assets/b2795b2d-2863-4cba-8621-c8fac3d91f2a)

**Comment by kyukyunyorituryo** [comment]
何を目的にするかによって違うのですが。

キンドルでの出版であれば、iOSでの配信はKindle Previewer 3どおりの表示になるようです。それは配信されるファイルとsend_to_kindleによって作られるファイルの形式が異なるようです。

iOSで読むだけならば、[Apple Books](https://www.apple.com/jp/apple-books/)のアプリがすでに入っていて表示に問題はないと思う。

**Comment by y-bonfire** [comment]
@kyukyunyorituryo 
コメントありがとうございます
AppleBooksなら読めるのですね、情報ありがとうございます
自分はKindle以外を使ってないので、そこにまとめられるのであればそれがありがたいです
この問題で困っている人が何人かいるみたいなので、その人達もAppleBooks使えばいいということを知らないのでしょうね…

ひとまずはKindleのiOSアプリ側の問題で対応してもらえるなら、それが一番良いと思っています
Amazonのサポートからメールで返信が来るという話になったので、まずはそれを待ちたいと思います

できればこのまま解決（＝アプリ側が対処される想定）までこのissueを使わせてもらえるとありがたいですが大丈夫でしょうか？
やりとりした結果解決しないという結果もありえますが、それはそれでクローズします

**Comment by y-bonfire** [comment]
2024/8/29
続報です
この件どうなっているのか不明でしたが、本日メールで返信が来てました
問題が確認できるepubファイルを送ってくれ、という内容だったので送っておきました
また今も問題が再現するか確認するように、ともあったので確認しておきました

**Comment by y-bonfire** [comment]
2024/10/9 
メールが帰ってきました
仕様ということでした
cssあたりに問題があると思ってるのですが、２ヶ月時間をかけて「仕様です」とだけ返す
調査や修正がそんなに難しい話ではないと思うので、わざとこのバグを残しているのかもしれませんね

>iOSのKindleアプリからEPUB ファイルの表示問題について、担当部署から返答が確認できましたので、ご連絡いたします。
恐れ入りますが、担当部署によりEPUB ファイルの表示はiOSのKindleアプリの仕様でございます。

**Comment by y-bonfire** [comment]
メールで教えてもらいましたが、opfファイルのlanguageの指定をjaでなくen指定で試してほしいということで試してみたところ、意図通りに表示されました

ja指定だと独自の変換が入るそうですがen指定ならそれがないからうまくいく、という理屈だそうです

item/standard.opf
```
before
<dc:language id="pub-lang">ja</dc:language>
after
<dc:language id="pub-lang">en</dc:language>
```

GUIでも”言語”のところで指定できるようになってますので、ここをデフォルトのjaでなくenで指定すれば解決です
なので本件は解決ということでクローズしようと思います

## 別の問題

リポジトリが更新されていたので最新にして試しましたが、別の問題が起きてるみたいで動作確認できませんでした
ドラッグアンドドロップはダメという注意があったのでファイル選択も試しましたが同様でした

確認したリビジョン 169a47aede268a618b560eb68a2e59dabde5c6c8

リリースから辿れる最新のビルドでも同様
https://github.com/kyukyunyorituryo/AozoraEpub3/releases

古いバージョンで動作確認しておきました
![image](https://github.com/user-attachments/assets/1efc4565-46d5-47ee-bb2e-dead4efd1025)

**Comment by kyukyunyorituryo** [comment]
日本語のEPUBからの変換がEPUB2で古いままなのかと思っています。

例外処理を調べていて書き換えてのが原因で止まっていたので、例外無視するようにした。
https://github.com/kyukyunyorituryo/AozoraEpub3/actions/runs/11250086731

**Comment by y-bonfire** [comment]
最新のリビジョン 1c3932cc6990bae3dcd4934618b23d38b72caf55 で動作確認しました
 epubが生成できることを確認しました
ご対応ありがとうございました
クローズします

**Comment by kyukyunyorituryo** [comment]
<metadata>タグ内に<meta name="primary-writing-mode" content="horizontal-rl"/>とツイッターで見つけた。

https://x.com/alltale2037/status/1852983738424271124

[Kindle パブリッシング・ガイドライン](https://kdp.amazon.co.jp/ja_JP/help/topic/GU72M65VRFPH43L6)にメタデータの追加とあったので追加する。

```
メタデータのガイドライン
デフォルトでは、電子書籍はリフロー型です。リフロー型の電子書籍では、OPF ファイルで meta name="book-type" を指定する必要はありませんが、<dc:language> および <dc:title> は必要です。ページめくりの方向が左から右ではない場合、メタデータまたは背表紙にページめくり方向を表示する必要があります。(例: <meta name="primary-writing-mode" content="horizontal-rl"/>)
```

https://x.com/99nyorituryo/status/1853101166986703053
https://kdp.amazon.co.jp/ja_JP/help/topic/GPNJPYK298J8TRRV
