### ISSUE TITLE
カクヨムの変換ができなくなる

### ISSUE THREAD

**Issue by gamephate** [kyukyunyorituryo/AozoraEpub3#4]
コメント失礼いたします。
急急如律令さんのおかげで、Web小説も気楽に電子書籍リーダーで読んで、ありがとうございます^^

が、最近カクヨムの小説が読み込めなくなったそうです。
（"一覧ページの取得に失敗しました。 "と表示しています）

もしよければ、手伝って確認していただけませんか。

**Comment by kyukyunyorituryo** [comment]
AozoraEpub3-1.1.1b12Q.x64_win.zipの方ではなくて、AozoraEpub3-1.1.1b12Q.zip方のjarを実行すると動くかもしれない。

**Comment by gamephate** [comment]
> AozoraEpub3-1.1.1b12Q.x64_win.zipの方ではなくて、AozoraEpub3-1.1.1b12Q.zip方のjarを実行すると動くかもしれない。

試してみると、確かにAozoraEpub3-1.1.1b12Q.zip方は正常に読み込めます！
ご答えありがとうございます^^
