### ISSUE TITLE
README.mdとREADME.txtで動作環境のバージョン記載が異なる

### ISSUE THREAD

**Issue by yochy4671** [kyukyunyorituryo/AozoraEpub3#6]
README.mdにはVersion:11と記載が、

https://github.com/kyukyunyorituryo/AozoraEpub3/blob/master/README.md?plain=1#L67

README.txtにはVersion:17と記載が

https://github.com/kyukyunyorituryo/AozoraEpub3/blob/master/README.txt#L23

あります。正しい方に記載を揃えていただけますか。

**Comment by kyukyunyorituryo** [comment]
v1.1.1b16Qで直しました
https://github.com/kyukyunyorituryo/AozoraEpub3/releases/tag/v1.1.1b16Q
