### ISSUE TITLE
AozoraEpub3-1.1.1b17Q.zip内にAozoraEpub3.jarが見当たらない

### ISSUE THREAD

**Issue by yochy4671** [kyukyunyorituryo/AozoraEpub3#7]
AozoraEpub3-1.1.1b17Q.zip内にAozoraEpub3.jarが見当たりません(b16Qにはある)。

https://github.com/kyukyunyorituryo/AozoraEpub3/blob/4fd89ac76b479fd0710d4f9c847eba6ef980c6b0/README.md?plain=1#L78

記載の起動ができないのですが、どうすればよいでしょうか。

**Comment by kyukyunyorituryo** [comment]
ダウンロードしたファイルは下記のアドレスのものでしょうか。確認しましたが、AozoraEpub3.jarは入っていました。
https://github.com/kyukyunyorituryo/AozoraEpub3/releases/download/v1.1.1b17Q/AozoraEpub3-1.1.1b17Q.zip
