### ISSUE TITLE
一部のライブラリ、ライセンス条文のファイルがありません

### ISSUE THREAD

**Issue by happynow** [kyukyunyorituryo/AozoraEpub3#9]
1.1.1b19Q のリリースファイルについてお聞きします。
Apacheの LICENSEファイルは AozoraEpub3.jar のなかで見つかりましたが
他のライブラリ、juniversalchardet-2.4.0.jar (MPL) や junrar-7.5.4.jar のなどはライセンス条文のコピーが見当たりません。
問題ありませんか。

ライセンスに疎いのでお聞きしますが、1.1.1b19Qより外部ライブラリをJARにパッケージングされてますが
一般的に利用ライブラリやライセンス条文をJARに含めることは問題ないのでしょうか。
特にライセンス条文のファイルは大丈夫なのかと気になります。質問になってしまい、すいません。

なお、1.1.1b19Q のリリースファイルは次のページから AozoraEpub3-1.1.1b19Q.zip をダウンロードしました。
https://github.com/kyukyunyorituryo/AozoraEpub3/releases/tag/v1.1.1b19Q

**Comment by kyukyunyorituryo** [comment]
jarとしてまとめた時に一緒にライセンスファイルを間違って消してしまっていたので修正版をアップロードしなおしました。

**Comment by happynow** [comment]
確認しました。対応ありがとうございました。
